### ISSUE TITLE
CDidlItem::size can returns 0 on 32bit compilers then value is larger the 32bit int limit.

### ISSUE THREAD

**Issue by lukesalisbury** [ptstream/QtUPnP#10]
Just a simple issue. Using qulonglong fixes it.
```
qulonglong CDidlItem::size (int index) const
{
  QList<CDidlElem> elems = m_d->m_elems.values ("res");
  int              size  = elems.size ();
  return index >= 0 && index < size ? elems[index].props ().value ("size").toULongLong() : 0;
}
```
System Info:
Windows 10 64bit
MinGW 5.3.0 32bit
Qt 5.11.1

**Comment by ptstream** [comment]
Hi, Lukesalisbury,

Thanks for your help.

I am not sure to understand the context of the problem (audio, image, video ...).
I see only one problem for this function. It is a video with a size greater than 4294967295 bytes (4 Gbytes). Is it your problem?

Thanks in advance.
Patrice

**Comment by lukesalisbury** [comment]
yes I came across it accessing info about video.

**Comment by ptstream** [comment]
Fixed and commit
Thanks for your help.
