### ISSUE TITLE
Servers/renderers working properly

### ISSUE THREAD

**Issue by PrzemoF** [ptstream/QtUPnP#16]
Info only after short tests, but seems to be working OK.
Server: minidlna on raspberry pi
Server: fedora 28 (rygel?)

Renderer (hardware/audio): Denon DRA-100
Renderer (hardware/video): LG TV webOS based 55B7V

Do you need any detailed info or export from chupnp?

**Comment by ptstream** [comment]
Hi,
Many thanks for your return. 
I am very happy that it works well with your system.
I will add your periphericals to the list.
If you have a problem later, certainly I would call on you for your peripherical details exported from chupnp.

Thank's again.
Patrice
