### ISSUE TITLE
Please add building instructions

### ISSUE THREAD

**Issue by PrzemoF** [ptstream/QtUPnP#17]
Please add building instructions or building script. I can help with fedora - what's the best format for you?

**Comment by ptstream** [comment]
Hi,
Thank's for your remark. 
It is true that I am not very explicit about the build 👎.
In the forder QtUPnP/aivctrl/install/linux64/ or QtUPnP/aivctrl/install/pi32/ your can launch build.sh.
This bash creates all that is necessary to build an installable version of aivctrl.
The sub-folder Output,  contains a Debian installer and a zip file for other Linux systems.
I hope this will help you.
Regards

**Comment by PrzemoF** [comment]
Thanks! Unfortunately they don't work on fedora. My build scripts are here: https://github.com/ptstream/QtUPnP/pull/18
Thanks for (probably) the best UPnP control software on linux desktop!
