### ISSUE TITLE
Using QtUPnP to open up TCP port on router

### ISSUE THREAD

**Issue by obiwankennedy** [ptstream/QtUPnP#2]
Thank for your work ! 
I need to use UPnP to open up tcp port on network device (as ISP boxes) but your library seems really complete and I don't want to include every thing. Is it possible to only use few classes to do what I want ? 

As the documentation is not online, I can't search by my self.  Example of some common use cases can be really appreciated. 

Moreover, I see some GUI code  (include widgets and some ui file). It may be useful to split view and working classes. 
What I have in mind:

In my projet.pro file:
include(qtupnp/core/core.pri)

In my source code:
```
//include header
#include "qtupnp/core/upnpmanager.hpp"
[...]
//create a manager 
upnpManager = new UpnpManager();
[...]
//Using - it can be asynchronus (if it is easier).
if(upnpManager->openPort(6660))
{
  log() << "Port open on device: Clients can join";
}
else 
{
switch((upnpManager->lastError())
case QtUPnP::ErrorPortAlreadyOpen:
  log() << "Port already open: Clients can join";
break;
 case QtUPnP::ErrorNoDeviceFound:
 case QtUPnP::ErrorUnsupportedDevice:
 case QtUPnP::ErrorWhatEver:
  log() << "Error: Clients can't join" << upnpManager->errorStr() ;
break:
}
```

**Comment by ptstream** [comment]
Hi obiwankennedy,

The project is divided in 3 parts:

1. Folder upnp is the library QtUPnP (dynamic for Windows and static for Linux) that encapsulates the protocol UPnP. This library does not contain any graphic API just some call to simplify the image management provided by UPnP periphericals (https://github.com/ptstream/QtUPnP/tree/master/upnp/).

2. Folder chupnp is the executable to test the library (https://github.com/ptstream/QtUPnP/tree/master/chupnp/). This executable is for developers.

3. Folder aivctrl is the control point, using QtUPnP, to manager UPnP/AV servers and renderers (https://github.com/ptstream/QtUPnP/tree/master/aivctrl/). This application cas be used by users and of course by developers.

The QtUPnP library documentation is https://github.com/ptstream/QtUPnP/tree/master/upnp/Doc/html.zip.

In your case, you will probably be interested only in QtUPnP folder.

I did some simple tests with Internet Gateway device, QtUPnP works with these periphericals.
With chupnp, you can see rapidly the exposed services.

Regards

**Comment by obiwankennedy** [comment]
ok ok if upnp is the library, why do you need gui, and widgets in the library .pro file ?

https://github.com/ptstream/QtUPnP/blob/master/upnp/upnp.pro 

Even if you don't have UI code your library is linked to it.

**Comment by ptstream** [comment]
Some small parts used QPixmap functions not widget functions and probably, QPixmap needs to used gui in the pro file.
In fact it is probably used only in CPixmapChache object.
I'm not sure if in the case of the static library and if you do not use CPixmapChache, X11 is used. I think that the linker extracts only the code call by the user.
But I did not do this test.

**Comment by ptstream** [comment]
Hi,
If you are already interest, I commited some changes to improve the managent of devices containing embedded devices (e.g.Internet Gateway Device).
I check these changes on my SFRBox (Netgear I think)
I also remove the reference at GUI in upnp.pro. Without reference at gui, the library builds on Windows and Linux without problem.
I also make some little changes in chupnp.
Regards
