### ISSUE TITLE
Tested on Synology DS120 & DS215j servers and Pioneer N-50 renderer

### ISSUE THREAD

**Issue by vyermakov** [ptstream/QtUPnP#21]
No issues fond. Works perfect.

**Comment by ptstream** [comment]
Hi Vjacheslav,
Many thanks for your return. 
If you have a little time, could you send me the system you are using.
•	Windows
•	Linux
•	MacOS
•	Raspberry

**Comment by vyermakov** [comment]
Sorry. Forgot about the important thing:  Windows 10. Version 10.0.19042.685.

Thank you for the control point app. The only one adequate upnp contol for Windows I found.
