### ISSUE TITLE
Two licence files  	LICENSE and license.txt

### ISSUE THREAD

**Issue by obiwankennedy** [ptstream/QtUPnP#3]
GPLv2 (license.txt) and GPLv3 (LICENSE)

**Comment by ptstream** [comment]
Thank for your reply.
I am not comfortable with license text and English, but after GPLv2 you will found "any later version". I think that this take in GPLv3.
Regards

**Comment by obiwankennedy** [comment]
Sure but your git repository has two license files even if there are compatibles it is not "clean". 
As v2 and v3 have some real differences for embedded software.  Confusion is honey in legal concern. Just select one and remove the other. 

Je suis d'accord qu'elles sont compatible mais avoir deux fichiers de licences est confus. Il y a des différences importantes entre les deux versions pour les logiciels embarqués. Cette confusion ne rend pas service. la bibliothèque car il y a un doute, un petit doute. Ce doute est du pain béni pour des juristes. C'est plus propre d'avoir un seul fichier de licence. Ainsi le message est clair.
