### ISSUE TITLE
build on windows

### ISSUE THREAD

**Issue by amigo421** [ptstream/QtUPnP#4]
have you tested the project on Win platform with cl compiler?
a lot of errors during the build , including in .pro file

**Comment by ptstream** [comment]
Hello,

Sorry, I don't make tests with cl compiler. I assume cl compiler is a Microsoft compiler.
I just make tests with MinGW on Windows and GCC on Linux.

Regards.

**Comment by ptstream** [comment]
Sorry, bad click, I reopen the issue.

**Comment by amigo421** [comment]
yes, that's right. latest visual c++ compiler can't compile.
this was just a question, not a real problem, so you can close the issue/question.

to avoid new issues raising, can I ask you here?

could you confirm the questions: I'm looking for the ability to scan and find video renderers (DLNA-enabled devices in local network) and forward existing media stream (MPEG TS) to there.
I see in an example that scanning works fine. but how is about my second question? 

P.S. why do you not use Qt coding style

**Comment by ptstream** [comment]
Hello,
To answer at your questions:

1. **I'm looking for the ability to scan and find video renderers (DLNA-enabled devices in local network) ?**
The Qt UPnP library is built for this. By default, the library retrieves all devices types, but you can limit the discovery to a device type.

2. **and forward existing media stream (MPEG TS) to there.**
QtUPnP don't stream anything. The library retreives the URL of medias (music, images, videos) on a server and sends one URL to a renderer. It is the responsability of the renderer to stream correctly the media. This is the operating mode of a control point as defined by the UPnP protocol.

3. **P.S. why do you not use Qt coding style**
It is a very very good question. I did this for several things (maybe not good things by the way):

- I chose not to interfere with future QT developments. Qt works actually on IoT. A lot of classes will be created (e.g. QDevice and CDevice for me).
- I am a very old developper, and sometimes it is difficult to change these habits.

However the syntax is close to that of QT accepted the first letter of a class definition.
Regards,
