### ISSUE TITLE
Mac Build

### ISSUE THREAD

**Issue by steveq61** [ptstream/QtUPnP#7]
Hey Patrice,

It wouldn't be the same if a week went by without me submitting a post! lol

A quick question, I tried to compile upnp on my Mac, and got some errors. I was able to correct the compilation errors by adding `#include <array>` to "**httpserver.hpp**" and "**xmlhdevice.hpp**". Consequently the program now compiles and links.

But it crashes when initiating a discover.
```
The program has unexpectedly finished.
The process was ended forcefully.
/Users/steveq/QT Apps/Home Automation/build-HomeAutomation-Desktop_Qt_5_9_3_clang_64bit-Debug/HomeLink/HomeLink.app/Contents/MacOS/HomeLink crashed.

Starting /Users/steveq/QT Apps/Home Automation/build-HomeAutomation-Desktop_Qt_5_9_3_clang_64bit-Debug/HomeLink/HomeLink.app/Contents/MacOS/HomeLink...
CMulticastSocket::initialize (joinMulticast): "239.255.255.250"
CMulticastSocket::~CMulticastSocket (leaveMulticastGroup): ""
CUpnpSocket::discover (write datagram): "239.255.255.250:1900"
CUpnpSocket::discover (write datagram): "239.255.255.250:1900"
The program has unexpectedly finished.
The process was ended forcefully.
/Users/steveq/QT Apps/Home Automation/build-HomeAutomation-Desktop_Qt_5_9_3_clang_64bit-Debug/HomeLink/HomeLink.app/Contents/MacOS/HomeLink crashed.
```

- I do realise you don't support Mac, but do you have any intention of adding support for Mac?
- Are these errors easy to fix?

Thanks Patrice,

Steve Q. :-)

**Comment by ptstream** [comment]
Hi Steve,
Difficult to solve the problem without MACOS.
If I examine your screenshot is see:
- CMulticastSocket::initialize is called. It is normal.
- The destructor ~CMulticastSocket is called. It is not normal.

I think the problem can be describe like this.
- CControlPoint::initializeMulticast is called line 42 of controlpoint.cpp (ok).
- The socket is created line 44 (ok)
- The socket is initialized is called line 45 (ok)
- CMulticastSocket::initialize line 27 of multicastsocket.cpp  (ok)
- The Socket is bind to ip address and port. The QT QAbstractSocket::bind fails probably.
- The others errors are the consequence of this fail.

I don't know why the QAbstractSocket::bind fails. The reasons are multiple.
- The multicast is not validate or protected in the system.
- The bind mode is QUdpSocket::ReuseAddressHint | QUdpSocket::ShareAddress. May be MACOS don't accept one of these 2 modes.

I think adding the support for MACOS is not difficult (I hope). But I do not have an Apple computer.
I have just  Windows, Ubuntu, Kubuntu and Rasbian systems.

Regards,
Patrice

**Comment by steveq61** [comment]
Hey Patrice,

I'm more than happy to work with you on developing the code to run on the MacOS if you would like. We can go to private emails so as not to flood this page until we get it working. Now I know where to look, I'll run the code in debug and see if I can narrow the problem down anymore.
If you would like to go further with this, let me know and I'll give you my email.

SQ :-)

**Comment by ptstream** [comment]
Hi,
No problem for this.
Above code tag on my GitHub page you can click on ptstream. You can see with this the public part of my account.
If you sign in your GitHub account, you can uses freely the email address. This address is public but it has not link with the GitHup used for issues, pull resquests.

![image](https://user-images.githubusercontent.com/18031408/39470894-814d82b4-4d40-11e8-9a10-51a34f8a99ab.png)

Patrice
