### ISSUE TITLE
Make install for aivctrl

### ISSUE THREAD

**Issue by v00d00** [ptstream/QtUPnP#8]
Hey, thanks for the project!

I ran (on Gentoo) a normal `qmake aivctrl.pro && make && make install`, but I only seem to get my destination folder?

```
./usr
./usr/lib
./usr/lib/libgoogledrive.so
./usr/lib/libgoogledrive.so.1
./usr/lib/libgoogledrive.so.1.0
```

Am I missing something?

**Comment by ptstream** [comment]
Hi, 

Sorry, I don't understand really the problem.
Probably aivctrl build not use strictly the Qt standard. 

**aivctrl is built, actually, with QtCreator.**

After build, a set of folders contains the binaries and files need to run aivctrl under QtCreator.

If you want create a full folder to run aivctrl, you must use two batch files.
- Windows QtUPnP/aivctrl/install/win32/build.cmd. It create a complet folder, **Output**, to run aivctrl.
- Linux  QtUPnP/aivctrl/install/linux64/build.sh. It create a complet folder, **QtUPnP/aivctrl/install/linux64/Output/debian/usr/bin/** to run aivctrl.

To build an installable version, on Windows you must used Innosetup application with the  **QtUPnP/aivctrl/install/win32/aivctrl.iss**
On Linux, build.sh create also for you a Debian package.

I hope I answered your questions.

Regards,
Patrice

**Comment by v00d00** [comment]
I guess my question is how to build for a Linux distribution that is not Debian, and without Qt creator?

Most projects that use qmake allow you to run qmake on a pro file, this generates normal Linux make files to build and install the software.

And indeed it does build the software!

However there seems to be no  "install set". See: http://doc.qt.io/qt-5/qmake-advanced-usage.html#Installing%20Files

Adding this would make life much easier for Linux users 👍

**Comment by ptstream** [comment]
Ok I understand.

For the moment, the bash file, QtUPnP/aivctrl/install/linux64/build.sh, creates a complet folder to run aivctrl.
This folder is independant of Linux distribution and Qt version installed on the computer (I hope). 
But, maybe,  aivctrl.pro is not ready to build outside QtCreator.
For the next version, I will study this. I never test it outside QtCreator. 

The README.md file contains a link to install aivctrl to test it.
This link points on a Google Drive folder who contains installable versions of aivctrl.
- Windows
- Linux 64 bits x86 processeur Dedian base
- All Linux 64 bits x86 processeur (all the necessary files in a folder)

I hope this help you to solve your problem temporary.

Regards
